events { worker_connections 1024; }
http {
    upstream node_backend {
        server app1:3000;
        server app2:3000;
    }
    server {
        listen 80;
        client_max_body_size 3M;
        location / { proxy_pass http://node_backend; }
    }
}